apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipmi-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ipmi-metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
