apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ipmi-exporter-cert
spec:
  isCA: true
  commonName: ipmi-exporter
  dnsNames:
    - ipmi-exporter
    - ipmi-exporter.ipmi-exporter.svc
    - ipmi-exporter.ipmi-exporter.svc.cluster.local
  secretName: ipmi-exporter-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca
    kind: Issuer
