apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ipmi-exporter
spec:
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      tlsConfig:
        ca:
          secret:
            name: internal-ca-cert
            key: tls.crt
        serverName: ipmi-exporter
      bearerTokenSecret:
        name: ipmi-exporter-sa-token
        key: token
      relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: instance
